/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package poi_validation;

import org.apache.poi.xssf.usermodel.XSSFWorkbook;

import java.io.FileInputStream;
import java.io.IOException;
import java.util.logging.Logger;

public class App {

    public static final String ROOT_PATH = "/Users/estefaniarv/Desktop/angel/development/practices/java/poi_validation";

    public static final Logger LOG = Logger.getLogger(App.class.getName());
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {


        try {
            var inputStream = new FileInputStream(ROOT_PATH + "/Libro1.xlsx");

            var book = new XSSFWorkbook(inputStream);

            var sheet = book.getSheetAt(0);

            var rowIterator = sheet.rowIterator();

            while(rowIterator.hasNext()){

                var cellIterator = rowIterator.next().cellIterator();

                while(cellIterator.hasNext()){
                    var cell = cellIterator.next();

                    LOG.info("coordenadas: " + cell.getAddress().formatAsString());
                    LOG.info("valor de celda: " + cell.getStringCellValue());

                }

            }

            inputStream.close();

        } catch (IOException e) {
            e.printStackTrace();
        }

    }

}
